### ISSUE TITLE
connect() got an unexpected keyword argument 'sock'

### ISSUE THREAD

**Issue by mfrey** [pkittenis/parallel-ssh#22]
Hi,
I'm not really sure if that's an issue of parallel-ssh, but if I try to execute a simple example. I get the following error
```python
aceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 538, in _exec_command
    proxy_port=self.proxy_port)
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 152, in __init__
    self._connect(self.client, self.host, self.port)
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 182, in _connect
    sock=sock, timeout=self.timeout)
TypeError: connect() got an unexpected keyword argument 'sock'
<Greenlet at 0x967766c: <bound method ParallelSSHClient._exec_command of <pssh.ParallelSSHClient object at 0x96bbf2c>>('t9-203', 'ls -ltrh /tmp/', sudo=True)> failed with TypeError

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 538, in _exec_command
    proxy_port=self.proxy_port)
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 152, in __init__
    self._connect(self.client, self.host, self.port)
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 182, in _connect
    sock=sock, timeout=self.timeout)
TypeError: connect() got an unexpected keyword argument 'sock'
<Greenlet at 0x96776ac: <bound method ParallelSSHClient._exec_command of <pssh.ParallelSSHClient object at 0x96bbf2c>>('t9-213', 'ls -ltrh /tmp/', sudo=True)> failed with TypeError

Traceback (most recent call last):
  File "./topology", line 46, in <module>
    main()
  File "./topology", line 42, in main
    writer.start_etxd()
  File "./topology", line 36, in start_etxd
    output = client.run_command('ls -ltrh /tmp/', sudo=True)
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 491, in run_command
    return self.get_output()
  File "/usr/local/lib/python2.7/dist-packages/pssh.py", line 578, in get_output
    (channel, host, stdout, stderr) = cmd.get()
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py", line 331, in get
    raise self._exception
TypeError: connect() got an unexpected keyword argument 'sock'
```
I've tried to find a solution for this issue but had no luck so far. On a [StackOverflow](http://stackoverflow.com/questions/13681341/fabric-used-as-library-not-working) thread somebody refers this to an issue of multiple installed ssh libraries. 

Do you have any ideas what might actually cause this issue? 

TIA!

** EDIT: This is my python path
```bash
mfrey@uhu:~/testbed$ python2.7 -c 'import sys; print(sys.path)'                 
['', '/testbed/bin/Scripts/lib', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-
linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/py
thon2.7/lib-dynload', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/di
st-packages/PIL', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodule
s/python2.7', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode']
```

**Comment by pkittenis** [comment]
The error is coming from paramiko. What is your installed paramiko version and how did you install paramiko? Via setup.py/requirements.txt or other?
